// @ts-nocheck
import * as __fd_glob_69 from "../content/docs/referencia-api/uplink/create-token.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/referencia-api/tokens/create-token.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/referencia-api/servidores/upload-server-icon.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/referencia-api/servidores/update-server.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/referencia-api/servidores/stream-release-logs.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/referencia-api/servidores/resume-release.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/referencia-api/servidores/publish-server.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/referencia-api/servidores/list-runtime-logs.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/referencia-api/servidores/list-releases.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/referencia-api/servidores/list-all-servers.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/referencia-api/servidores/get-server.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/referencia-api/servidores/get-server-icon.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/referencia-api/servidores/get-release.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/referencia-api/servidores/download-bundle.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/referencia-api/servidores/delete-server.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/referencia-api/servidores/delete-server-icon.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/referencia-api/servidores/create-server.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/referencia-api/namespaces/list-namespaces.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/referencia-api/namespaces/delete-namespace.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/referencia-api/namespaces/create-server-ns.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/referencia-api/namespaces/create-namespace.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/referencia-api/namespaces/create-generated.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/referencia-api/introduccion/health-check.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/referencia-api/herramientas/update-skill.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/referencia-api/herramientas/list-skills.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/referencia-api/herramientas/get-skill.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/referencia-api/herramientas/delete-skill.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/referencia-api/herramientas/create-skill.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/referencia-api/connect-mcp/mcp-endpoint.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/referencia-api/connect/update-connection.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/referencia-api/connect/list-connections.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/referencia-api/connect/get-connection.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/referencia-api/connect/delete-connection.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/referencia-api/connect/create-connection.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/servers/session-config.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/servers/publish.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/servers/overview.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/recetas/cliente-oauth.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/primeros-pasos/introduccion.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/primeros-pasos/conectar-servidores.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/integraciones/vercel-ai-sdk.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/herramientas/ine.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/herramientas/borme.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/herramientas/boe.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/herramientas/aemet.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/conceptos/spainmcp-cli.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/conceptos/que-es-mcp.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/conceptos/namespaces.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/clientes/token-scoping.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/clientes/listar-cliente.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/clientes/introduccion.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/clientes/deep-linking.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/clientes/conectar-mcps.mdx?collection=docs"
import { default as __fd_glob_16 } from "../content/docs/referencia-api/uplink/meta.json?collection=docs"
import { default as __fd_glob_15 } from "../content/docs/referencia-api/servidores/meta.json?collection=docs"
import { default as __fd_glob_14 } from "../content/docs/referencia-api/tokens/meta.json?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/referencia-api/namespaces/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/referencia-api/connect-mcp/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/referencia-api/herramientas/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/referencia-api/introduccion/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/referencia-api/connect/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/servers/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/referencia-api/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/recetas/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/primeros-pasos/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/integraciones/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/clientes/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/conceptos/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/herramientas/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "herramientas/meta.json": __fd_glob_1, "conceptos/meta.json": __fd_glob_2, "clientes/meta.json": __fd_glob_3, "integraciones/meta.json": __fd_glob_4, "primeros-pasos/meta.json": __fd_glob_5, "recetas/meta.json": __fd_glob_6, "referencia-api/meta.json": __fd_glob_7, "servers/meta.json": __fd_glob_8, "referencia-api/connect/meta.json": __fd_glob_9, "referencia-api/introduccion/meta.json": __fd_glob_10, "referencia-api/herramientas/meta.json": __fd_glob_11, "referencia-api/connect-mcp/meta.json": __fd_glob_12, "referencia-api/namespaces/meta.json": __fd_glob_13, "referencia-api/tokens/meta.json": __fd_glob_14, "referencia-api/servidores/meta.json": __fd_glob_15, "referencia-api/uplink/meta.json": __fd_glob_16, }, {"clientes/conectar-mcps.mdx": __fd_glob_17, "clientes/deep-linking.mdx": __fd_glob_18, "clientes/introduccion.mdx": __fd_glob_19, "clientes/listar-cliente.mdx": __fd_glob_20, "clientes/token-scoping.mdx": __fd_glob_21, "conceptos/namespaces.mdx": __fd_glob_22, "conceptos/que-es-mcp.mdx": __fd_glob_23, "conceptos/spainmcp-cli.mdx": __fd_glob_24, "herramientas/aemet.mdx": __fd_glob_25, "herramientas/boe.mdx": __fd_glob_26, "herramientas/borme.mdx": __fd_glob_27, "herramientas/ine.mdx": __fd_glob_28, "integraciones/vercel-ai-sdk.mdx": __fd_glob_29, "primeros-pasos/conectar-servidores.mdx": __fd_glob_30, "primeros-pasos/introduccion.mdx": __fd_glob_31, "recetas/cliente-oauth.mdx": __fd_glob_32, "servers/overview.mdx": __fd_glob_33, "servers/publish.mdx": __fd_glob_34, "servers/session-config.mdx": __fd_glob_35, "referencia-api/connect/create-connection.mdx": __fd_glob_36, "referencia-api/connect/delete-connection.mdx": __fd_glob_37, "referencia-api/connect/get-connection.mdx": __fd_glob_38, "referencia-api/connect/list-connections.mdx": __fd_glob_39, "referencia-api/connect/update-connection.mdx": __fd_glob_40, "referencia-api/connect-mcp/mcp-endpoint.mdx": __fd_glob_41, "referencia-api/herramientas/create-skill.mdx": __fd_glob_42, "referencia-api/herramientas/delete-skill.mdx": __fd_glob_43, "referencia-api/herramientas/get-skill.mdx": __fd_glob_44, "referencia-api/herramientas/list-skills.mdx": __fd_glob_45, "referencia-api/herramientas/update-skill.mdx": __fd_glob_46, "referencia-api/introduccion/health-check.mdx": __fd_glob_47, "referencia-api/namespaces/create-generated.mdx": __fd_glob_48, "referencia-api/namespaces/create-namespace.mdx": __fd_glob_49, "referencia-api/namespaces/create-server-ns.mdx": __fd_glob_50, "referencia-api/namespaces/delete-namespace.mdx": __fd_glob_51, "referencia-api/namespaces/list-namespaces.mdx": __fd_glob_52, "referencia-api/servidores/create-server.mdx": __fd_glob_53, "referencia-api/servidores/delete-server-icon.mdx": __fd_glob_54, "referencia-api/servidores/delete-server.mdx": __fd_glob_55, "referencia-api/servidores/download-bundle.mdx": __fd_glob_56, "referencia-api/servidores/get-release.mdx": __fd_glob_57, "referencia-api/servidores/get-server-icon.mdx": __fd_glob_58, "referencia-api/servidores/get-server.mdx": __fd_glob_59, "referencia-api/servidores/list-all-servers.mdx": __fd_glob_60, "referencia-api/servidores/list-releases.mdx": __fd_glob_61, "referencia-api/servidores/list-runtime-logs.mdx": __fd_glob_62, "referencia-api/servidores/publish-server.mdx": __fd_glob_63, "referencia-api/servidores/resume-release.mdx": __fd_glob_64, "referencia-api/servidores/stream-release-logs.mdx": __fd_glob_65, "referencia-api/servidores/update-server.mdx": __fd_glob_66, "referencia-api/servidores/upload-server-icon.mdx": __fd_glob_67, "referencia-api/tokens/create-token.mdx": __fd_glob_68, "referencia-api/uplink/create-token.mdx": __fd_glob_69, });